### ISSUE TITLE
[Feature] 过滤组件时间粒度支持更多选项

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#14281] opened 2024-12-24 03:53 UTC
DataEase 版本:
2.10.3

**请描述您的需求或者改进建议.**
过滤组件时间粒度支持更多选项
![image](https://github.com/user-attachments/assets/6945ae29-d569-4abe-a6cb-a32a4c4f3332)
支持周、季度等选项
<img width="345" alt="image" src="https://github.com/user-attachments/assets/aaf0c6de-c152-4094-9b71-cd94b7c4c5ad" />

**Comment by xuwei-fit2cloud** [comment] 2024-12-24 10:21
Duplicate of #14280

**Closed as completed by xuwei-fit2cloud** 2024-12-24 10:21 UTC
Labels: 类型:需求
