### ISSUE TITLE
[Feature] 柱状图支持 Small multiples，类似于 powerbi

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#13532] opened 2024-11-25 07:54 UTC
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
柱状图支持 Small multiples，类似于 powerbi
![image](https://github.com/user-attachments/assets/94e7c41c-b543-4a2f-ad11-06af98b12a36)

**Comment by xuwei-fit2cloud** [comment] 2024-11-25 10:21
Duplicate of #12712

**Closed as completed by xuwei-fit2cloud** 2024-11-25 10:21 UTC
Labels: 类型:需求
